name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install packages
        run: make install
      
      - name: Format code
        run: make format
      
      - name: Lint code
        run: make lint
      
      - name: Run tests
        run: make test
