name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: List files for debugging
        run: ls -R
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build -f $GITHUB_WORKSPACE/.devcontainer/Dockerfile -t python-dev .
            
      - name: Run Docker container
        run: docker run --rm -v /home/runner/work/Nruta_Mini_Project_1/Nruta_Mini_Project_1:/workspace -p 8000:8000 python-dev
      
      - name: Install packages
        run: make install
      
      - name: Format code
        run: make format
      
      - name: Lint code
        run: make lint
      
      - name: Run tests
        run: make test